= Pipeline Architecture

[plantuml]
....
!include <awslib/AWSCommon>
!include <awslib/AWSSimplified>
!include <awslib/Compute/all>
!include <awslib/mobile/all>
!include <awslib/general/all>
!include <awslib/GroupIcons/all>
!include <awslib/ApplicationIntegration/all>
!include <tupadr3/common>
!include <tupadr3/devicons/github_badge>

Users(dev, "Developer", "")
DEV_GITHUB_BADGE(github, "GitHub")

APIGateway(webhook, "External Entrypoint", "")

Lambda(github_handler, "GitHub Handler", "")
Lambda(deployment_creator, "Deployment Creator", "")
Lambda(terraform_trigger, "Deployment Trigger", "")
Lambda(status_updater, "GitHub Deployment Status Updater", "")
Fargate(terraform_deployer, "Terraform Runtime", "")

SQS(queue_repos, "Updated Repos", "")
SQS(queue_deployment, "Environment Deployment", "")
SQS(queue_deployment_status, "Deployment Status", "")

Cloudalt(environment, "Environment", "")


dev -> github
github --> webhook : New commits on master
webhook -> github_handler
github_handler -> queue_repos

queue_repos -> deployment_creator
deployment_creator -> queue_deployment

queue_deployment -> terraform_trigger
terraform_trigger -> terraform_deployer
terraform_deployer -> environment

deployment_creator --> queue_deployment_status : Deployment queued
terraform_trigger --> queue_deployment_status : Deployment in progress
terraform_deployer --> queue_deployment_status : Deployment finished/failed
queue_deployment_status -> status_updater
status_updater -> github


dev -> webhook : Approve deployment
....

== Responsibilities

The principle here is to have the CI engine do the bulk of the work, and then

CircleCI::
* Responsible for the flow of integration and deployment.

AWS Pipeline::
* Responsible for actually deploying resources.
* Check if test and stage got updated before production (IMPORTANT)

== Security Conciderations

* Verify the hash of the artifact for each stage.
  The hash can't change for a deployment.

== Related resources

Check out NCSCs CI/CD security principles!
https://www.ncsc.gov.uk/collection/developers-collection/principles/secure-the-build-and-deployment-pipeline
