= AWS Deployment Pipeline
:toc:
:!toc-placement:
:!toc-title:

A deployment pipeline for provisioning your resources into AWS!
Configured in YAML, and aiming at being simple to use.

toc::[]

== About

This module gives your environment a deployment pipeline for your applications.
Using a simple YAML file, you can deploy any repo you want!

Here is how simple it can be to deploy a terraform repository:

[source, yaml]
----
# .deployment/config.yaml

# This defines what each environment should do on deployment.
deployment:
  steps:
    - deploy_terraform:
        version: 1.0.8

# This is the order that deployments happen.
# In this case it's first service, test and stage that gets deployed.
# Production then deploys when those are successful.
flow:
  - [service, test, stage]
  - prod
----

== Examples

In the link:examples/[examples directory] you can find multiple examples.
These can be helpful to set up the pipeline in your own team!

link:examples/pipeline_setup[Pipeline Setup]::
This example shows you how to set up the pipeline for your account set.
It is specifically for your `<team>-aws` repository.

== Features

The pipeline has some features that make your life easier.
All the following examples are top level stanzas that you can just drop right into your configuration.

=== Deployment Order

Deploy your environments in any order you want!
Want to be a madman and deploy production first?
Go ahead (but please don't).

[source,yaml]
----
flow:
  - [service, test, stage]
  - prod
----

=== Keep Versions Up To Date

Specify applications you want to always keep up to date, based on a tag.

[source,yaml]
----
applications:
  ecr:
    - name: demo-container
      tag_filters: [master-branch]
  lambda:
    - name: demo-serverless
      tag_filters: [master-branch]
  frontend:
    - name: demo-frontend
      tag_filters: [master-branch]
----


== Setup

First, we need to make sure the pipeline has permission to deploy to all the relevant accounts.
This is done via the extra permission module.

[source,hcl-terraform]
----
module "deployment_pipeline_permissions" {
  source = "github.com/nsbno/terraform-aws-delivery-pipeline//extras/permissions"

  name_prefix = "deployment"
  service_account_id = local.service_account_id
}
----

Now, lets add the actual pipeline to our environment.
Place this module in your `service` account.

[source,hcl-terraform]
----
module "deployment_pipeline" {
  source = "github.com/nsbno/terraform-aws-delivery-pipeline/"

  name_prefix = "deployment"

  deployment_accounts = {
    service = "1111111111"
    test = "2222222222"
    stage = "3333333333"
    prod = "4444444444"
  }

  deployment_role = module.deployment_pipeline_permissions.deployment_role
  set_version_role = module.deployment_pipeline_permissions.set_version_role

  account_id = "1111111111"
  subnets = module.vpc.public_subnet_ids
}
----

You can now move onto creating a configuration for each repo that you want to deploy 🎉

== Usage

// TODO: Details about the different parts of the YAML config.
